<?php

/**
 * Represents a system for caching packages generated by a PackageGenerator
 */
interface PackageCache {

	/**
	 * Generate or retrieve a package from the cache
	 *
	 * @param PackageGenerator $generator The generator to use to create cache entries.
	 * @param string $identifier A unique identifier for the generator; used to partition the cache
	 * @param string $sha The SHA of the commit to be deployed
	 * @param string $repositoryDir The directory where the repository resides
	 * @param DeploynautLogFile $log The log to write status output to, including package-generation commands
	 */
	public function getPackageFilename(
		PackageGenerator $generator,
		$identifier,
		$sha,
		$repositoryDir,
		DeploynautLogFile $log
	);
}
