#!/bin/bash

# Continually requests that the CheckPipelineStatus controller do its work.
# This way, we don't let PHP leak memory by constantly running.

ROOT="/sites/deploynaut/www"

while true
do
	cd $ROOT
	framework/sake CheckPipelineStatus
	sleep 5s # sleep for 5 seconds before running again
done
